### ISSUE TITLE
Incorrect Path

### ISSUE THREAD

**Issue by ijuintekka** [8890q/android_device_samsung_universal8895-common#1]
Underscore instead of slash in samsung_slsi causes early build failure.

https://github.com/8890q/android_device_samsung_universal8895-common/blob/85344fa0f0131a47c2f1cd90c5505c549f54d119/BoardConfigCommon.mk#L150

**Comment by ivanmeler** [comment]
> Underscore instead of slash in samsung_slsi causes early build failure.
> 
> https://github.com/8890q/android_device_samsung_universal8895-common/blob/85344fa0f0131a47c2f1cd90c5505c549f54d119/BoardConfigCommon.mk#L150

Well no this is not incorrect, you synced samsung_slsi repo to wrong folder its supposed to be synced to device/samsung_slsi/sepolicy.
Please consider you did something wrong instead of filling bogus bug reports next time

**Comment by ijuintekka** [comment]
With respect, the thought of possibly being wrong was never absent. It is not my intention to cause offence, I am only attempting to learn.

Most of the Lineage sync and build process is automated and, lacking any kind of instruction, during this process there is no opportunity to choose where and how things are synced beyond using the local manifest. The path names are populated automatically and https://github.com/LineageOS/android_device_samsung_slsi_sepolicy does not have its underscore preserved, it becomes two subdirectories.

My first thought from your response is that I remove the sepolicy project using the local manifest then re-add it with a different path. This seems absurdly redundant, so if I'm wrong can you tell me what I'm missing?

**Comment by ivanmeler** [comment]
> With respect, the thought of possibly being wrong was never absent. It is not my intention to cause offence, I am only attempting to learn.
> 
> Most of the Lineage sync and build process is automated and, lacking any kind of instruction, during this process there is no opportunity to choose where and how things are synced beyond using the local manifest. The path names are populated automatically and https://github.com/LineageOS/android_device_samsung_slsi_sepolicy does not have its underscore preserved, it becomes two subdirectories.
> 
> My first thought from your response is that I remove the sepolicy project using the local manifest then re-add it with a different path. This seems absurdly redundant, so if I'm wrong can you tell me what I'm missing?

Have you even tried to open that repo instead of blindly trying to build, repo itself would show you what has to be included and where its supposed to be cloned (https://github.com/LineageOS/android_device_samsung_slsi_sepolicy/blob/lineage-19.1/README.md), you should not blindly assume anything and look at https://github.com/8890q/android_device_samsung_universal8895-common/blob/lineage-19.1/lineage.dependencies

Furthermore sync 8890q repos instead of LineageOS ones as there tend to be changes that are not upstream yet and in 8890q repos

**Comment by ijuintekka** [comment]
My apologies for lacking this knowledge. I'll try to be omniscient in the future.

I would not be here were I not syncing the 8890q repos.

So you are in effect confirming that I need to remove the sepolicy repo and re-add it using a different directory name. Thanks, I guess.
